#!/bin/bash

STORMFRONTD_HOST="$1"
STORMFRONTD_PORT="$2"
COMMAND="$3"

case $COMMAND in
    deploy)
        curl -X POST http://${STORMFRONTD_HOST}:${STORMFRONTD_PORT}/api/daemon/deploy
        ;;
    destroy)
        curl -X DELETE http://${STORMFRONTD_HOST}:${STORMFRONTD_PORT}/api/daemon/destroy
        ;;
    restart)
        curl -X POST http://${STORMFRONTD_HOST}:${STORMFRONTD_PORT}/api/daemon/restart
        ;;
    help)
        echo "Valid commands are: deploy, destory, restart, help"
        exit 0
        ;;
    *)
        echo "Invalid command: ${COMMAND}"
        echo "Valid commands are: deploy, destroy, restart, help"
        exit 1
        ;;
esac
